### ISSUE TITLE
freezeframe ignores gif width

### ISSUE THREAD

**Issue by jhelvy** [gadenbuie/xaringanExtra#103]
I'm finding that when I include `xaringanExtra::use_freezeframe()`, gifs freeze correctly but the width is ignored. It always resizes to the full gif size. Here's an example:

````
---
title: "Freezeframe reprex"
date: March 30, 2021
output:
  xaringan::moon_reader:
    lib_dir: libs
    seal: false
    nature:
      ratio: "16:9"
---

```{r setup, include=FALSE}
xaringanExtra::use_freezeframe()
```

## Should be 300px wide, but switches to full size

<center>
<img src="https://github.com/zumbov2/votemapswitzerland/raw/main/animation1.gif" width=300>
</center>

---

## Full size for comparison

<center>
<img src="https://github.com/zumbov2/votemapswitzerland/raw/main/animation1.gif">
</center>
````

**Comment by gadenbuie** [comment]
I'm on the fence about this one. I think that `responsive = FALSE` could be a good default; it's essentially what happens when you use plain `![](keyboard-cat.gif)` syntax. 

On the other hand, images are stretched to 100% width by default so `![](keyboard-cat.png)` would have been 100% width. My sense is that most people would prefer gifs were displayed at 100% width and currently have to use work-arounds to get animated images to be the size they want. So that's why I stuck with the freezeframe.js default of `responsive = TRUE`.

On the other other hand, I'm sure it's just as likely that responsive images will cause problems for some people who will need to figure out how to turn it off or to adjust the image size by putting the gif in a width-constrained container.

In the end I settled on following the freezeframe default, hence `responsive = TRUE`.

**Comment by BerriJ** [comment]
While `use_freezeframe()` works for me when using html syntax:

```
<center>
<img src="weights_lambda.gif">
</center>
```

It does not when using markdown:

`![](weights_lambda.gif)`

I played around with the "selector" argument a little bit but could not get it working. I'm happy for advice on how to debug this.

Im using the [sidney theme ](https://github.com/garthtarr/sydney_xaringan) but nothing really exotic afaik.

**Comment by gadenbuie** [comment]
@BerriJ The sydney theme does include a zooming plugin for remark that might be interfering with Freezeframe. Can you confirm that you also encounter the problem with the default theme? In either case, would you mind opening a new issue with a small example?

**Comment by BerriJ** [comment]
@gadenbuie Thank you very much. I just created a reprex and during the strip-down to make it as minimal as possible I discovered that the self_contained option causes the problem. I created an issue for this as you suggested: #115 Thank you very much.

**Comment by yadav-rohit** [comment]
Hi, I am having the same issue as I was working on one of my react projects with react-freezeframe.js. I am not able to change the size of the gif
