### ISSUE TITLE
Tachyons .grow[] does not work

### ISSUE THREAD

**Issue by albert-ying** [gadenbuie/xaringanExtra#104]
Hi, I enabled `xaringanExtra::use_tachyons()`. After explored the document of Tachyons, I found an interesting hover animation function `.grow` and `.dim`.

But when I put `.grow[ text ]` in the R Markdown file, it does not work. I'm wondering if this feature is supported?

**Comment by gadenbuie** [comment]
The `.grow` class uses the CSS property `transform` to scale up the element on hover. But `transform` only applies to block element, not inline elements. Since `.grow[text]` is rendered as `<span class="grow">text</span>` and spans are inline elements, the transformation won't be applied.

You _can_ get around this by making the element an inline block element. Try using `.grow.dib[text]` instead.

**Comment by albert-ying** [comment]
Works like magic! Thank you!
