### ISSUE TITLE
Fullscreen doesn't work for presentation embedded in table

### ISSUE THREAD

**Issue by mattwarkentin** [gadenbuie/xaringanExtra#120]
Hey @gadenbuie,

Any idea why the full screen functionality wouldn't work for a `xaringan` presentation embedded in a table? I am creating a table of presentations for the lab I belong to, and I want the HTML presentations embedded in the table, like below:
```r
library(reactable)
library(tidyverse)
library(xaringanExtra)
library(htmltools)

data <- tribble(
  ~Date, ~Time, ~Name, ~Title, ~Link,
  "2021-07-10", "2PM ET", "Matt", "Reproducible and scalable data analysis workflows with targets", "https://mattwarkentin.github.io/targets-demo/#1"
) 

data %>%
  reactable(
    columns = list(
      Link = colDef(show = FALSE)
    ),
    details = function(i) {
      div(
        embed_xaringan(
          url = data$Link[[i]], 
          style = c("height: 400px", "width: 711px")
        ),
        style = "display: flex; justify-content: center;"
      )
    }
  )
```

The other buttons (e.g. change slides, share button) work, but full screen doesn't...

**Comment by gadenbuie** [comment]
You're running up against a quirk of how React handles HTML attributes. For full screen to work, the `<iframe>` element needs the boolean attribute `allowfullscreen`. In HTML, boolean attribute values are indicated by _presence_ or _abscence_ of the attribute:

```html
<!-- this iframe allows fullscreen -->
<iframe allowfullscreen></iframe>

<!-- this iframe does not -->
<iframe></iframe>
```

Unfortunately, React handles boolean attributes differently. For react to give you the correct answer, you need the HTML

```html
<iframe allowfullscreen=true></iframe>
```

Extra unfortunately, it's almost impossible to write that kind of tag with htmltools. 😞 

```r
library(htmltools)
iframe <- tags$iframe

iframe(allowfullscreen = NA)
## <iframe allowfullscreen></iframe>

iframe(allowfullscreen = TRUE)
## <iframe allowfullscreen="TRUE"></iframe>

iframe(allowfullscreen = "true")
## <iframe allowfullscreen="true"></iframe>

iframe(allowfullscreen = HTML("true"))
## <iframe allowfullscreen="true"></iframe>

HTML("<iframe allowfullscreen=true></iframe>")
## <iframe allowfullscreen=true></iframe>
```

I can think of two options, but I'm not certain either will work.

1. Construct the HTML in strings. You'd need to use `colDef(html = TRUE)` and you'd also need to include the [share again dependencies](https://github.com/gadenbuie/xaringanExtra/blob/c34c65d9ba9faa9db6974b6ace879bff9aafa99e/R/share_again.R#L142-L143) directly in the document elsewhere.
1. Construct the HTML in [a JavaScript function](https://glin.github.io/reactable/articles/custom-rendering.html) provided to `details`. Again, you'd need to include the share again deps manually.

I'm going to close this issue because I don't think there's much we can do in xaringanExtra, but please do post a solution if you discover one. And also link to your page of slides, the one in the reprex looks great and I've been wanting to learn more about targets! 😉
