### ISSUE TITLE
[panelset] Handle tab overflow and multiline tabs

### ISSUE THREAD

**Issue by realauggieheschmeyer** [gadenbuie/xaringanExtra#39]
Is there an option somewhere to resize the labels of panels? I may be asking too much of the package, but I would like to have 11 panels and they're running off the side of the slide.

![image](https://user-images.githubusercontent.com/45769104/90016235-ad018b80-dc77-11ea-939f-fb2d581ce750.png)

Any help or guidance you can provide would be appreciated. Thank you.

**Comment by gadenbuie** [comment]
Thanks for bringing this up! I have three strategies that will work right now, but I need a better solution for this in the long term.

1. Separate the tabs into 2 slides with 5 & 6 tabs (this is my top recommendation)

1. You can reduce the font size of the tabs with this CSS chunk, just drop into your slides Rmd and adjust `font-size` as needed.

    ````markdown
    ```css
    .panelset .panel-tabs {
      font-size: 0.8rem;
    }
    ```
    ````

1. You can also change with font used for the tabs with this chunk (the argument name may change with #37):

    ````markdown
    ```{r echo=FALSE}
    xaringanExtra::style_panelset(panel_tab_font_family = "sans-serif")
    ```
    ````

***

Two issues that I noticed here that I need to take care of

- [ ] Handle tab overflow in parent `ul.panel-tabs`
- [ ] Ensure tabs fill `ul.panel-tabs` completely so that the hover bottom border lines up correctly
    
    ![image](https://user-images.githubusercontent.com/5420529/90021544-6c0d7500-dc7f-11ea-82db-498771e5c50a.png)

<details><summary>Reprex</summary>

````markdown
---
output:
  xaringan::moon_reader:
    seal: false
---

```{r}
xaringanExtra::use_panelset()
xaringanExtra::style_panelset(panel_tab_font_family = "sans-serif")
```

```{r echo=FALSE}
htmltools::div(
  class = "panelset",
  lapply(
    stringr::fruit[1:11],
    function(name) {
      htmltools::div(
        class = "panel",
        htmltools::span(class = "panel-name", name),
        htmltools::p(lorem::ipsum(1, 3))
      )
    }
  )
)
```
````

</details>

**Comment by realauggieheschmeyer** [comment]
Thank you for the advice!
