### ISSUE TITLE
Panelset freezes on Safari

### ISSUE THREAD

**Issue by jvcasillas** [gadenbuie/xaringanExtra#50]
When using multiple panelsets in my `xaringan` slides (i.e., in different slides but several times over the course of a presentation) I notice that by browser freezes from time to time. Specifically, I am no longer able to move forward or backward in the presentation using arrows or by typing the number of the slide I'd like to move to. My current workaround is to simple reload the presentation (cntr + r) and then continue, at which point the arrow keys work as normal. I initially thought it may have something to do with using the same names for panelsets (i.e., "code", "plot") over the course of the presentations, but I have tested with different names and get the same issue. This behavior doesn't seem to occur when I use firefox.

**Comment by gadenbuie** [comment]
Yikes, thanks for the report! Are any of these slides online so I could take a look?

**Comment by jvcasillas** [comment]
Not a problem! Thank you for this wonderful package. This should work for you: 

https://www.jvcasillas.com/slides/00_programa/index.html#1

**Comment by gadenbuie** [comment]
This is a bizarre error, but I've figured out the source (sort of). Basically, as a security measure, Safari doesn't let JS re-write the browser URL too often. Both remarkjs and I do this -- remarkjs adds the slide number, e.g. `#5`, and I add information about which panelset is selected.

But sometimes, because I repeatedly call `history.replaceState()` to update the URL with the currently selected panelset or to scrub panelset selection from the URL when leaving a panelset slide, the `history.replaceState()` calls can happen too quickly, causing Safari to throw this error:

```
SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
```

What makes it odd is that I can recreate the error locally, but only when I try really hard, like holding down the left or right arrow key to move too fast through slides. On the other hand, it happens reliably with little effort in the slides linked above. I can't find anything that might possibly be interacting with remark to explain the difference.

I'll need to rewrite the `updateUrl` JavScript function to avoid repeated URL updates.

In the meantime, in addition to reloading the slides, you can also try using a different browser. I don't think Firefox or Chrome will have this problem.

**Comment by jvcasillas** [comment]
> What makes it odd is that I can recreate the error locally, but only when I try really hard, like holding down the left or right arrow key to move too fast through slides. On the other hand, it happens reliably with little effort in the slides linked above. I can't find anything that might possibly be interacting with remark to explain the difference.

This is definitely odd. I get the error scrolling through my slides at a more or less normal pace. I wonder if it has to do with any other js I use? See [here](https://www.jvcasillas.com/ru_xaringan/js/ru_xaringan.js) and also https://use.fontawesome.com/5235085b15.js.

**Comment by gadenbuie** [comment]
Hi @jvcasillas I just refactored the JavaScript to update the URL as few times as possible. This should mitigate or even eliminate the problem, as long as you aren't flipping through slides as fast as you can.

Can you test with the latest version of xaringanExtra and let me know if it works for you? Thanks!

**Comment by jvcasillas** [comment]
Awesome. I'll give it a go now and report back.

**Comment by jvcasillas** [comment]
Works perfect (even if I hold down the arrow and scroll through super fast). Great stuff. Thank you!
