### ISSUE TITLE
Panelset and not repeating code

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [gadenbuie/xaringanExtra#53]
I was hoping to use panelset to show code in one panel and the resulting plot/output and the other. I expected the following to work putting together the examples on the xaringanExtra page and [here](https://arm.rbind.io/slides/xaringan.html#98). However, the plot on the second panel doesn't show up. Am I missing something or is this a bug? Thank you!

**Code:**

```
    ---
    output:
      xaringan::moon_reader:
        lib_dir: libs
    ---
    
    ```{r xaringan-panelset, echo=FALSE}
    xaringanExtra::use_panelset()
    ```
    
    .panelset[
    .panel[.panel-name[R Code]
    
    ```{r panel-chunk, fig.show='hide'}
    plot(cars)
    ```
    ]
    
    .panel[.panel-name[Plot]
    ```{r ref.label="panel-chunk", echo=FALSE}
    ```
    ]
    ]
```

**Output:**

<img width="500" alt="Screenshot 2020-09-03 at 19 50 42" src="https://user-images.githubusercontent.com/5965649/92155188-e06eaa80-ee1e-11ea-91b2-1ef783614095.png">
<img width="500" alt="Screenshot 2020-09-03 at 19 51 09" src="https://user-images.githubusercontent.com/5965649/92155192-e2386e00-ee1e-11ea-8b86-cb204b9068f4.png">

**Comment by gadenbuie** [comment]
Yeah, that is odd! What version of `xaringanExtra` are you using? It might be helpful to take a look at `devtools::session_info()`, because `rmarkdown` and `pandoc` versions might be at play (but unlikely...). Also what browser?

This is what I see when I render with xaringanExtra versions `0.2.0` through `0.2.2`

<img width="899" alt="image" src="https://user-images.githubusercontent.com/5420529/92156909-a50cb580-edf7-11ea-8651-ea4ce2f89b81.png">

I'm about to merge a PR with a few panelset improvements, you could also try again after #52 lands.

**Comment by mine-cetinkaya-rundel** [comment]
It's working now with the most recent changes, thank you!
