### ISSUE TITLE
Panelset reading code chunk content as markdown

### ISSUE THREAD

**Issue by spcanelon** [gadenbuie/xaringanExtra#71]
Hi again @gadenbuie 👋 

I'm having some trouble using code chunks with panelset and haven't run into this issue before. For some reason anything that even resembles markdown gets turned into markdown inside panels. Any suggestions you have would be much appreciated 😃 

These screenshots come from an RStudio Cloud project, and the code chunk content for both is:

```
---
class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`
---
```

![image](https://user-images.githubusercontent.com/49913337/97895356-ad9f4080-1d01-11eb-952e-07ea7758e691.png)
![image](https://user-images.githubusercontent.com/49913337/97895413-bd1e8980-1d01-11eb-8ea6-bfed631120f5.png)

**Comment by gadenbuie** [comment]
Can you share the source code for the slides with the panelset?

**Comment by spcanelon** [comment]
Here are the files exported from the Cloud project:

[rstudio-export-panelset.zip](https://github.com/gadenbuie/xaringanExtra/files/5476732/rstudio-export-panelset.zip)

**Comment by gadenbuie** [comment]
I think this is a problem with the markdown parser in remarkjs, since I get the same results without including panelset.

You can get the markdown parser to skip the code chunk processing by using `<pre><code>` in html rather than markdown:

````
.panelset[
.panel[.panel-name[Example]
<pre><code>---
class: title-slide, left, bottom

# `r '\x60r rmarkdown::metadata$title\x60'`
----
## **`r '\x60r rmarkdown::metadata$subtitle\x60'`**
### `r '\x60r rmarkdown::metadata$author\x60'`
### `r '\x60r rmarkdown::metadata$date\x60'`
---</code></pre>

]
]
````

I think you might be wanting to show the `rmarkdown::metadata$title` as verbatim inline code, i.e. including the backtick + `r`, so I used [this trick from Yihui](https://stackoverflow.com/a/20419016).

![image](https://user-images.githubusercontent.com/5420529/97904311-4dfb6200-1d0e-11eb-9890-b73a40857f6a.png)

**Comment by spcanelon** [comment]
🎉 I just breathed a huge sigh of relief, this is such a big help. 
Thanks so much Garrett!

**Comment by spcanelon** [comment]
I wish I could "undo" that last comment with the embarrassing typo! 🤦‍♀️ 
I promise I actually do know your name. 

Thanks for all of your help **Garrick**! It's much appreciated.

**Comment by gadenbuie** [comment]
You're welcome! And no worries 😄
