### ISSUE TITLE
[panelset] panelset chunk option breaks line highlighting

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#99]
These don't work

````
.panelset[
```{r test, panelset = TRUE, results="hold"}
runif(5)
runif(2) #<<
runif(3)
```
```{r test, panelset = TRUE, results="hold", highlight.lines = 2}
runif(5)
runif(2)
runif(3)
```
]
````

**Comment by mine-cetinkaya-rundel** [comment]
I just came across this as well and came here to open an issue, happy to see it's already here!

I love the panelset feature and use it heavily in teaching. The shortcut for `panelset` with data visualization code is especially helpful since it's generally difficult to fit code and plot in the same slide. I also use highlighting regularly in teaching. All that to say, a huge upvote from me for this issue 😄
